#g++ -std=c++11 -O2 -mavx2 -c classify.cpp
# CC=g++
# CFLAGS=-std=c++11 -O2 -g

# sources=main.cpp
# objects=$(sources:.cpp=.o)

# classify:$(objects)
# 	$(CC) $(CFLAGS) -fopenmp $^ -o $@

# run: classify
# 	./classify rfile dfile 1009072 4 10

# %.o: %.cpp classify.h
# 	$(CC) $(CFLAGS) -fopenmp -c $<

# clean:
# 	rm *.o classify

run:
	g++ -o exec main.cpp